version: '3.4'

services:
  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - connectionString=Data Source=tcp:localhost,1433;Initial Catalog=IdenityServerDB;Persist Security Info=False;User ID=sa;Password=ApplicationMarket2019!
    ports:
      - "5000:80"

  apiresource:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  mvcclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"


  apiresource2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"

